process module sets separately from components
tweag/okapi pull request #7
Opened 2021-10-04 13:27 UTC by tek

This extracts the module spec from dune into a separate data structure that is converted to rules separately from executables and libraries.

The PR also fixes the problem that executable main files were included in the dependencies of other executables.

Hope I caught all randomizations in the tests!

2021-10-04 16:13 UTC, sir4ur0n requested changes

2021-10-04 16:13 UTC, sir4ur0n commented on example/project-2/exe/BUILD.bazel
> +    name = "exe-exe",
Please rename the executable name in the Dune file to clearly see it's `name-exe` and not `exe-name` or even constant `exe-exe` :smile:

2021-10-04 16:13 UTC, sir4ur0n commented on lang/dune.go
>  	// TODO add here the map[moduleKey]ModuleSpec here
Shouldn't this TODO be removed?

2021-10-04 16:13 UTC, sir4ur0n commented on lang/dune.go
> +  var cnames []ComponentName
How about making the name more explicit? E.g. `componentNames`

2021-10-04 16:13 UTC, sir4ur0n commented on lang/dune.go
> +  modules int
What do you think about renaming to `modulesIndex`?

2021-10-04 16:13 UTC, sir4ur0n commented on lang/dune.go
> +  modules int
Open question: what would be the pros/cons of directly using a pointer of `ModuleSpec` here? If `ModuleSpec` is immutable then this would have the same effect but simpler (and safer), wouldn't it?

2021-10-04 16:13 UTC, sir4ur0n commented on lang/dune.go
>    for _, gen := range spec.generated { gens = append(gens, gen) }
Is this different from `gens := spec.generated`?

2021-10-04 16:13 UTC, sir4ur0n commented on lang/dune.go
>        }
Can't we use `else if` directly?

2021-10-04 16:13 UTC, sir4ur0n commented on lang/dune.go
>    }
Can't we simplify as such?
```go
for _, gen := range gens {
  for i, srcSpec := range spec.modules {
    _, exists := byGen[gen]
    if (srcSpec.modules.auto() && !exists) || srcSpec.modules.specifies(gen) {
      byGen[gen] = i
    }
  }
}
```

2021-10-04 16:13 UTC, sir4ur0n commented on lang/generate.go
> +// TODO this needs to return the modules to be added to `PackageSpec` now
Shouldn't this be implemented? Or should we open an issue instead?

2021-10-04 16:13 UTC, sir4ur0n commented on lang/lang.go
> +    // results = AmendRules(args, args.File.Rules, Dependencies(args.Dir, args.RegularFiles), *config.library)
TODO

2021-10-04 16:15 UTC, tek commented on lang/dune.go
> +  modules int
`ModuleSpec` is transformed into other data structures and with a pointer, the connection would be lost. If you can think of a way to preserve that, please go ahead

2021-10-04 16:16 UTC, tek commented on lang/dune.go
>    for _, gen := range spec.generated { gens = append(gens, gen) }
probably not!

2021-10-05 12:49 UTC, sir4ur0n commented on lang/generate.go
> +// TODO this needs to return the modules to be added to `PackageSpec` now
Opened https://github.com/tweag/okapi/issues/9 as followup

2021-10-05 13:05 UTC, merged